default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues:
        - generation
      threads: 2
      processes: 1
      polling_interval: 1

    - queues:
        - default
        - low_priority
      threads: 2
      processes: 1
      polling_interval: 1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
